##### 요구사항
* 공연기간을 시작일과 종료일로 나누어 두 개의 컬럼에 넣기 <br>
* 현재일 기준으로 종료된 공연 삭제 <br>
* 'URL' 결측치에 기본 프로필 이미지 넣기 <br>
* 모든 사이트의 공연데이터를 하나로 합치기 <br>

In [31]:
import pandas as pd
import numpy as np

In [32]:
df_link = pd.read_csv('../ticketMerge/티켓머지_일정데이터/ticketLink_data.csv')

In [33]:
df_link.head(2)

,상품 제목,포스터 URL,상세 포스터 URL,공연장소,공연기간,캐스팅 리스트,해당 링크
0,2024 이승철 신곡발매기념 콘서트 “Rock'n All” - 서울,https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_8...,올림픽공원 올림픽홀,2024.06.29-2024.06.30,['이승철'],https://www.ticketlink.co.kr/product/50125
1,Soundberry Festa’ 24,https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_1...,KBS아레나 일대,2024.07.20-2024.07.21,[],https://www.ticketlink.co.kr/product/50492

In [34]:
# 결측치 확인하기

In [35]:
df_link.isna().sum()

상품 제목         0
포스터 URL       0
상세 포스터 URL    4
공연장소          0
공연기간          0
캐스팅 리스트       0
해당 링크         0
dtype: int64

In [36]:
# 공연기간을 시작일/종료일 두 컬럼으로 나누기

In [37]:
dt_link = pd.DataFrame(df_link['공연기간'])

In [38]:
dt_link

                      공연기간
0    2024.06.29-2024.06.30
1    2024.07.20-2024.07.21
2    2024.08.03-2024.08.04
3    2024.08.28-2024.08.28
4    2024.07.12-2024.07.13
..                     ...
117  2024.09.25-2024.09.25
118  2024.09.28-2024.09.28
119  2024.10.31-2024.10.31
120  2024.11.03-2024.11.03
121  2024.12.11-2024.12.11

[122 rows x 1 columns]

In [39]:
# "-"를 기준으로 공연기간을 분리하여 새로운 컬럼 추가

In [40]:
dt_link = dt_link[['시작일', '종료일']] = dt_link['공연기간'].str.split('-', expand=True)

In [41]:
dt_link

              0           1         시작일         종료일
0    2024.06.29  2024.06.30  2024.06.29  2024.06.30
1    2024.07.20  2024.07.21  2024.07.20  2024.07.21
2    2024.08.03  2024.08.04  2024.08.03  2024.08.04
3    2024.08.28  2024.08.28  2024.08.28  2024.08.28
4    2024.07.12  2024.07.13  2024.07.12  2024.07.13
..          ...         ...         ...         ...
117  2024.09.25  2024.09.25  2024.09.25  2024.09.25
118  2024.09.28  2024.09.28  2024.09.28  2024.09.28
119  2024.10.31  2024.10.31  2024.10.31  2024.10.31
120  2024.11.03  2024.11.03  2024.11.03  2024.11.03
121  2024.12.11  2024.12.11  2024.12.11  2024.12.11

[122 rows x 4 columns]

In [42]:
# 필요 없어진 컬럼 삭제
dt_link = dt_link.drop(columns=[0,1])

In [43]:
dt_link

            시작일         종료일
0    2024.06.29  2024.06.30
1    2024.07.20  2024.07.21
2    2024.08.03  2024.08.04
3    2024.08.28  2024.08.28
4    2024.07.12  2024.07.13
..          ...         ...
117  2024.09.25  2024.09.25
118  2024.09.28  2024.09.28
119  2024.10.31  2024.10.31
120  2024.11.03  2024.11.03
121  2024.12.11  2024.12.11

[122 rows x 2 columns]

In [44]:
# 시작일과 종료일의 결측치 확인하기
# 종료일에 결측치가 있을 경우, 시작일 값으로 채우기 위해서

In [45]:
dt_link.isna().sum()

시작일    0
종료일    0
dtype: int64

In [46]:
# dt_link 데이터 프레임을 원래 데이터프레임에 합치기

In [47]:
df_link = pd.concat([df_link, dt_link], axis=1)

In [48]:
df_link

,상품 제목,포스터 URL,상세 포스터 URL,공연장소,공연기간,캐스팅 리스트,해당 링크,시작일,종료일
0,2024 이승철 신곡발매기념 콘서트 “Rock'n All” - 서울,https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_8...,올림픽공원 올림픽홀,2024.06.29-2024.06.30,['이승철'],https://www.ticketlink.co.kr/product/50125,2024.06.29,2024.06.30
1,Soundberry Festa’ 24,https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_1...,KBS아레나 일대,2024.07.20-2024.07.21,[],https://www.ticketlink.co.kr/product/50492,2024.07.20,2024.07.21
2,이승환밴드 마지막 팬미팅,https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_9...,연세대학교 백주년기념관 콘서트홀,2024.08.03-2024.08.04,['이승환밴드'],https://www.ticketlink.co.kr/product/50709,2024.08.03,2024.08.04
3,EMOTIONAL ORANGES (이모셔널 오렌지스) 첫 단독 내한 공연,https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_1...,예스24 라이브홀,2024.08.28-2024.08.28,"['EMOTIONAL ORANGES', 'CHIIILD']",https://www.ticketlink.co.kr/product/50396,2024.08.28,2024.08.28
4,LILPACON : Going Out - SOOPER CONCERT,https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_1...,경희대학교 평화의전당,2024.07.12-2024.07.13,['이세계아이돌 릴파'],https://www.ticketlink.co.kr/product/50487,2024.07.12,2024.07.13
...,...,...,...,...,...,...,...,...,...
117,더 피아니스트 재즈 - 안동,https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_2...,안동문화예술의전당 백조홀,2024.09.25-2024.09.25,['상세정보 참고'],https://www.ticketlink.co.kr/product/50230,2024.09.25,2024.09.25
118,"2024 정태춘,박은옥 콘서트 - 전주",https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_9...,전북대학교 삼성문화회관,2024.09.28-2024.09.28,"['정태춘', '박은옥']",https://www.ticketlink.co.kr/product/50562,2024.09.28,2024.09.28
119,홍기쁨 아코디언의 세계일주 - 안동,https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_1...,안동문화예술의전당 백조홀,2024.10.31-2024.10.31,['상세정보 참고'],https://www.ticketlink.co.kr/product/50228,2024.10.31,2024.10.31
120,2024 김창옥 토크콘서트 시즌4 - 원주,https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_3...,원주 백운아트홀,2024.11.03-2024.11.03,['김창옥'],https://www.ticketlink.co.kr/product/49733,2024.11.03,2024.11.03
121,2024 인문학과 함께하는 브런치콘서트 - 궤도,https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_5...,대구 아양아트센터 아양홀,2024.12.11-2024.12.11,['궤도'],https://www.ticketlink.co.kr/product/48236,2024.12.11,2024.12.11

In [49]:
# 공연기간 컬럼 삭제하기

In [50]:
df_link = df_link.drop(['공연기간'], axis=1)

In [51]:
df_link.head(1)

,상품 제목,포스터 URL,상세 포스터 URL,공연장소,캐스팅 리스트,해당 링크,시작일,종료일
0,2024 이승철 신곡발매기념 콘서트 “Rock'n All” - 서울,https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_8...,올림픽공원 올림픽홀,['이승철'],https://www.ticketlink.co.kr/product/50125,2024.06.29,2024.06.30

In [52]:
df_link.isna().sum()

상품 제목         0
포스터 URL       0
상세 포스터 URL    4
공연장소          0
캐스팅 리스트       0
해당 링크         0
시작일           0
종료일           0
dtype: int64

In [53]:
# 상세 포스터 URL 결측치에 나무위키 이미지 넣어주기
# 나무위키 빈 이미지 : https://i.namu.wiki/i/GFw2SMaGiqbS3yeTWO08FD5Df8LKk-xB2ckQ0MtDjdoryMCJtsDap9msW17NVgbTM4432kao4DkEGsgwhs_In0zw9vMOldvNbYoc-n1Ng4XgxBVZXNZz33WScPw6zCJY5XAVrdsAFGDx24HN_nu3oQ.webp

In [54]:
df_link['상세 포스터 URL'].fillna('https://i.namu.wiki/i/GFw2SMaGiqbS3yeTWO08FD5Df8LKk-xB2ckQ0MtDjdoryMCJtsDap9msW17NVgbTM4432kao4DkEGsgwhs_In0zw9vMOldvNbYoc-n1Ng4XgxBVZXNZz33WScPw6zCJY5XAVrdsAFGDx24HN_nu3oQ.webp', inplace=True)

In [55]:
df_link.isna().sum()

상품 제목         0
포스터 URL       0
상세 포스터 URL    0
공연장소          0
캐스팅 리스트       0
해당 링크         0
시작일           0
종료일           0
dtype: int64

In [56]:
df_link.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   상품 제목       122 non-null    object
 1   포스터 URL     122 non-null    object
 2   상세 포스터 URL  122 non-null    object
 3   공연장소        122 non-null    object
 4   캐스팅 리스트     122 non-null    object
 5   해당 링크       122 non-null    object
 6   시작일         122 non-null    object
 7   종료일         122 non-null    object
dtypes: object(8)
memory usage: 7.8+ KB

In [26]:
# 종료일을 'date' 데이터 타입으로 변환하고 현재일 기준으로, 종료된 공연 삭제하기

In [57]:
pd.to_datetime(df_link['종료일'])

ValueError: time data " 2024.07.13" doesn't match format "%Y.%m.%d", at position 33. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [58]:
df_link['종료일'] = df_link['종료일'].str.strip()

ValueError: time data " 2024.07.13" doesn't match format "%Y.%m.%d", at position 33. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

    * 공백이 있는 데이터로 인해 에러가 생겨서, strip() 함수로 공백제거함.

In [75]:
# '종료일_date' 컬럼 추가하기

In [73]:
df_link['종료일_date'] = pd.to_datetime(df_link['종료일'])

In [74]:
df_link.head(2)

,상품 제목,포스터 URL,상세 포스터 URL,공연장소,캐스팅 리스트,해당 링크,시작일,종료일,종료일_date
1,Soundberry Festa’ 24,https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_1...,KBS아레나 일대,,https://www.ticketlink.co.kr/product/50492,2024.07.20,2024.07.21,2024-07-21
2,이승환밴드 마지막 팬미팅,https://image.toast.com/aaaaab/ticketlink/TKL_...,http://image.toast.com/aaaaab/ticketlink/TKL_9...,연세대학교 백주년기념관 콘서트홀,이승환밴드,https://www.ticketlink.co.kr/product/50709,2024.08.03,2024.08.04,2024-08-04

In [76]:
import datetime as dt

In [77]:
dt.datetime.now()

datetime.datetime(2024, 7, 5, 15, 19, 36, 86934)

In [78]:
current = dt.datetime.now()

In [79]:
df_link = df_link[df_link['종료일_date'] >= current]

In [80]:
df_link['종료일_date'] >= current

1      True
2      True
3      True
4      True
5      True
       ...
117    True
118    True
119    True
120    True
121    True
Name: 종료일_date, Length: 109, dtype: bool

In [81]:
# 캐스팅 리스트에서 가수 이름을 , 로 구별하여 나열하기
# [ , ] , '  문자 삭제하기

In [82]:
df_link['캐스팅 리스트'] = df_link['캐스팅 리스트'].str.replace('[', '').str.replace(']', '').str.replace("'", "")

In [84]:
df_link['캐스팅 리스트']

1
2                           이승환밴드
3      EMOTIONAL ORANGES, CHIIILD
4                       이세계아이돌 릴파
5                             김현중
                  ...
117                       상세정보 참고
118                      정태춘, 박은옥
119                       상세정보 참고
120                           김창옥
121                            궤도
Name: 캐스팅 리스트, Length: 109, dtype: object

In [ ]:
# csv 파일로 저장하기

In [85]:
df_link.to_csv('../ticketMerge/df_link.csv')

#### 가수데이터 정리하기

In [86]:
artist_link = pd.read_csv('../ticketMerge/티켓머지_아티스트데이터/ticketLink_artist.csv')

In [87]:
artist_link

,이름,URL
0,['이승철'],https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
1,['이승환밴드'],https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
2,"['EMOTIONAL ORANGES', 'CHIIILD']",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
3,['이세계아이돌 릴파'],https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
4,['김현중'],https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
...,...,...
71,['김창완'],https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
72,['심수봉'],https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
73,"['정태춘', '박은옥']",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
74,['김창옥'],https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
75,['궤도'],https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...

In [ ]:
# 가수이름 정리하기

In [90]:
artist_link['이름'] = artist_link['이름'].str.replace('[', '').str.replace(']', '').str.replace("'", "")

C:\Users\406\AppData\Local\Temp\ipykernel_8216\1583697655.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  artist_link['이름'] = artist_link['이름'].str.replace('[', '').str.replace(']', '').str.replace("'", "")

In [91]:
artist_link

,이름,URL
0,이승철,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
1,이승환밴드,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
2,"EMOTIONAL ORANGES, CHIIILD",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
3,이세계아이돌 릴파,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
4,김현중,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
5,ARTMS,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
6,허회경,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
7,니엘,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
8,tripleS (트리플에스),https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
9,LiSA,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
10,윤딴딴,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
11,헤이즈 x 로꼬,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
12,강형호,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
13,허지원,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
14,"10일 대니초, 김동하, 송하빈, 김영구, 박철현 11일 김동하, 이제규, 손동훈...",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
17,김태균,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
19,015B,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
20,김기태,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
21,노사연,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
22,"QM, 프롬올투휴먼",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
23,샤메이,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
24,PITTA 강형호,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
25,"원혁 (특별출연 개그맨 이용식, 이수민)",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
26,박인희,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
27,김창옥,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
28,변진섭,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
30,이은결,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
31,"최정원, 홍지민, 뮤지컬단 윙크 등",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
32,최형배,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
33,"박성호, 김원효, 김재욱, 정범균, 이종훈",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
34,김창완,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
35,김경호,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
36,"강진, 김용임, 진성",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
37,뮤지컬단 다락,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
38,윤수일밴드,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
39,"부활, 플라워, izi, 이정봉, Bigdaddy",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
40,원팩트,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
41,"Pile, 닛타에미",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
42,라쿠나,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
43,심수봉,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
45,너드커넥션,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
46,"설호승(보컬&기타), 이한빈(베이스), 오명석(드럼), 김도연(기타)",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
47,"김용임, 진성",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
48,김창완밴드,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
49,마술사 이경재,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
51,김정민,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
52,커트 로젠윈클,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
54,김성규,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
55,"이영현, 박민혜, 여동생",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
56,"양지원, 빈예서, 최수호",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
57,현동헌,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
63,Piano 카즈미 타테이시 Contrabass 시노부 사토 Drums 마오 스즈키,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
64,존 리,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
65,"카즈미 타테이시 트리오, 요시다 케이코, 젠틀레인",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
66,"정동하, 알리",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
68,남진,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
69,프레드 허쉬,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
70,임진모,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
73,"정태춘, 박은옥",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
75,궤도,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...

In [92]:
artist_link.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 0 to 75
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      60 non-null     object
 1   URL     60 non-null     object
dtypes: object(2)
memory usage: 1.4+ KB

In [ ]:
# 중복 데이터 제거하기

In [93]:
artist_link = artist_link.drop_duplicates()

In [94]:
# csv 파일로 저장하기

In [95]:
artist_link.to_csv('../ticketMerge/artist_link.csv')