In [91]:
import pandas as pd
import numpy as np

In [92]:
df1 = pd.read_csv('../ticketMerge/artist_inpark.csv')

In [93]:
df2 = pd.read_csv('../ticketMerge/artist_melon.csv')

In [94]:
df3 = pd.read_csv('../ticketMerge/artist_link.csv')

In [95]:
df4 = pd.read_csv('../ticketMerge/artist_yes.csv')

In [96]:
df1

     Unnamed: 0       이름                                                URL
0             0      트레저  https://ticketimage.interpark.com/PlayDictiona...
1             1    두아 리파  https://ticketimage.interpark.com/PlayDictiona...
2             2       싸이  https://ticketimage.interpark.com/PlayDictiona...
3             7      이문세  https://ticketimage.interpark.com/PlayDictiona...
4             9    SG워너비  https://ticketimage.interpark.com/PlayDictiona...
..          ...      ...                                                ...
142         180   마오 스즈키  https://ticketimage.interpark.com/PlayDictiona...
143         181   시노부 사토  https://ticketimage.interpark.com/PlayDictiona...
144         182  요시다 케이코  https://ticketimage.interpark.com/PlayDictiona...
145         183       소향  https://ticketimage.interpark.com/PlayDictiona...
146         184      정동하  https://ticketimage.interpark.com/PlayDictiona...

[147 rows x 3 columns]

In [97]:
df2

,Unnamed: 0,이름,URL
0,0,HYUN),https://cdnimg.melon.co.kr/cm2/artistcrop/imag...
1,1,IVE (아이브),https://cdnimg.melon.co.kr/cm2/artistcrop/imag...
2,2,박서준,https://cdnimg.melon.co.kr/cm/artistcrop/image...
3,3,이준형,https://cdnimg.melon.co.kr/cm2/artistcrop/imag...
4,4,쿠기 (Coogie),https://cdnimg.melon.co.kr/cm2/artistcrop/imag...
...,...,...,...
159,188,젠틀레인 (Gentle Rain),https://cdnimg.melon.co.kr/cm2/artistcrop/imag...
160,189,RIIZE,https://cdnimg.melon.co.kr/cm2/artistcrop/imag...
161,190,Matt Maltese,https://cdnimg.melon.co.kr/cm/artistcrop/image...
162,191,Chihiro Yamazaki+Route 14 Band,https://cdnimg.melon.co.kr/cm2/artistcrop/imag...
163,192,A-FUZZ (에이퍼즈),https://cdnimg.melon.co.kr/cm2/artistcrop/imag...

In [98]:
df3

,Unnamed: 0,이름,URL
0,0,이승철,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
1,1,이승환밴드,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
2,2,"EMOTIONAL ORANGES, CHIIILD",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
3,3,이세계아이돌 릴파,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
4,4,김현중,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
5,5,ARTMS,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
6,6,허회경,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
7,7,니엘,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
8,8,tripleS (트리플에스),https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
9,9,LiSA,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
10,10,윤딴딴,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
11,11,헤이즈 x 로꼬,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
12,12,강형호,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
13,13,허지원,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
14,14,"10일 대니초, 김동하, 송하빈, 김영구, 박철현 11일 김동하, 이제규, 손동훈...",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
15,17,김태균,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
16,19,015B,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
17,20,김기태,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
18,21,노사연,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
19,22,"QM, 프롬올투휴먼",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
20,23,샤메이,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
21,24,PITTA 강형호,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
22,25,"원혁 (특별출연 개그맨 이용식, 이수민)",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
23,26,박인희,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
24,27,김창옥,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
25,28,변진섭,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
26,30,이은결,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
27,31,"최정원, 홍지민, 뮤지컬단 윙크 등",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
28,32,최형배,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
29,33,"박성호, 김원효, 김재욱, 정범균, 이종훈",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
30,34,김창완,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
31,35,김경호,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
32,36,"강진, 김용임, 진성",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
33,37,뮤지컬단 다락,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
34,38,윤수일밴드,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
35,39,"부활, 플라워, izi, 이정봉, Bigdaddy",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
36,40,원팩트,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
37,41,"Pile, 닛타에미",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
38,42,라쿠나,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
39,43,심수봉,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
40,45,너드커넥션,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
41,46,"설호승(보컬&기타), 이한빈(베이스), 오명석(드럼), 김도연(기타)",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
42,47,"김용임, 진성",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
43,48,김창완밴드,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
44,49,마술사 이경재,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
45,51,김정민,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
46,52,커트 로젠윈클,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
47,54,김성규,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
48,55,"이영현, 박민혜, 여동생",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
49,56,"양지원, 빈예서, 최수호",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
50,57,현동헌,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
51,63,Piano 카즈미 타테이시 Contrabass 시노부 사토 Drums 마오 스즈키,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
52,64,존 리,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
53,65,"카즈미 타테이시 트리오, 요시다 케이코, 젠틀레인",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
54,66,"정동하, 알리",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
55,68,남진,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
56,69,프레드 허쉬,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
57,70,임진모,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
58,73,"정태춘, 박은옥",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
59,75,궤도,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...

In [99]:
df4

,Unnamed: 0,이름,URL
0,0,배너(VANNER),https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
1,1,더보이즈 (THE BOYZ),https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
2,2,이찬원,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
3,3,바다(BADA),https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
4,4,WOOAH,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
...,...,...,...
62,73,CHO TOKIMEKI SENDENBU,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
63,74,eaJ,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
64,75,"EMOTIONAL ORANGES, CHIIILD",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
65,76,NEKIRU,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
66,77,NMIXX,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...

In [100]:
# 모든 데이터 합치기

In [101]:
df = pd.concat([df1,df2,df3,df4], ignore_index=True)

In [102]:
df

,Unnamed: 0,이름,URL
0,0,트레저,https://ticketimage.interpark.com/PlayDictiona...
1,1,두아 리파,https://ticketimage.interpark.com/PlayDictiona...
2,2,싸이,https://ticketimage.interpark.com/PlayDictiona...
3,7,이문세,https://ticketimage.interpark.com/PlayDictiona...
4,9,SG워너비,https://ticketimage.interpark.com/PlayDictiona...
...,...,...,...
433,73,CHO TOKIMEKI SENDENBU,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
434,74,eaJ,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
435,75,"EMOTIONAL ORANGES, CHIIILD",https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
436,76,NEKIRU,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
437,77,NMIXX,https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...

In [103]:
# 필요없는 컬럼 삭제하기

In [104]:
df = df.drop(['Unnamed: 0'], axis=1)

In [105]:
# '이름' 컬럼값을 쉼표(,)로 분리하여 새로운 행 생성

In [106]:
artists = df['이름'].str.split(', ').explode().reset_index(drop=True)

In [107]:
artists

0                    트레저
1                  두아 리파
2                     싸이
3                    이문세
4                  SG워너비
             ...
597                  eaJ
598    EMOTIONAL ORANGES
599              CHIIILD
600               NEKIRU
601                NMIXX
Name: 이름, Length: 602, dtype: object

In [108]:
# artists 데이터를 포함하는 새로운 데이터프레임 생성

In [109]:
df_new = pd.DataFrame(artists)

In [110]:
df_new

                    이름
0                  트레저
1                두아 리파
2                   싸이
3                  이문세
4                SG워너비
..                 ...
597                eaJ
598  EMOTIONAL ORANGES
599            CHIIILD
600             NEKIRU
601              NMIXX

[602 rows x 1 columns]

In [111]:
# df_new 를 합치기전에 df에서 동일한 컬럼 삭제하기

In [112]:
df = df.drop(['이름'], axis=1)

In [113]:
# 두 데이터프레임 합치기

In [114]:
df = pd.concat([df_new, df], axis=1)

In [115]:
df

                    이름                                                URL
0                  트레저  https://ticketimage.interpark.com/PlayDictiona...
1                두아 리파  https://ticketimage.interpark.com/PlayDictiona...
2                   싸이  https://ticketimage.interpark.com/PlayDictiona...
3                  이문세  https://ticketimage.interpark.com/PlayDictiona...
4                SG워너비  https://ticketimage.interpark.com/PlayDictiona...
..                 ...                                                ...
597                eaJ                                                NaN
598  EMOTIONAL ORANGES                                                NaN
599            CHIIILD                                                NaN
600             NEKIRU                                                NaN
601              NMIXX                                                NaN

[602 rows x 2 columns]

In [116]:
# URL 컬럼 비어있는 자리에 기본 이미지 주소 넣어주기

In [117]:
df['URL'] = df['URL'].fillna('https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQJij2SngwNssjpjaOyOqoRhQlNwLrR2ZiK-JWJ2b99RGcSxDaZ2UCI7fiv4IDDQ.webp')

In [118]:
# 결측치 확인하기

In [119]:
df.isna().sum()

이름     0
URL    0
dtype: int64

In [120]:
# Unnamed: 0 컬럼 생기지 않도록 저장하기

In [121]:
df.to_csv('../ticketMerge/artist_total.csv', index=False)

##### 요구사항
컬럼명 테이블 명세서 보고 변경하기, 각 사이트에서 동시 판매하는 공연의 경우 가수명이 중복되서 들어갈 수 있기 때문에, 중복 데이터 제거하기

In [79]:
# 파일 불러와서 df 변수명으로 저장하기

In [123]:
df = pd.read_csv('../ticketMerge/artist_total.csv')

In [125]:
df

                    이름                                                URL
0                  트레저  https://ticketimage.interpark.com/PlayDictiona...
1                두아 리파  https://ticketimage.interpark.com/PlayDictiona...
2                   싸이  https://ticketimage.interpark.com/PlayDictiona...
3                  이문세  https://ticketimage.interpark.com/PlayDictiona...
4                SG워너비  https://ticketimage.interpark.com/PlayDictiona...
..                 ...                                                ...
597                eaJ  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
598  EMOTIONAL ORANGES  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
599            CHIIILD  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
600             NEKIRU  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
601              NMIXX  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...

[602 rows x 2 columns]

In [126]:
df.columns = ['name', 'url']

In [127]:
df

                  name                                                url
0                  트레저  https://ticketimage.interpark.com/PlayDictiona...
1                두아 리파  https://ticketimage.interpark.com/PlayDictiona...
2                   싸이  https://ticketimage.interpark.com/PlayDictiona...
3                  이문세  https://ticketimage.interpark.com/PlayDictiona...
4                SG워너비  https://ticketimage.interpark.com/PlayDictiona...
..                 ...                                                ...
597                eaJ  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
598  EMOTIONAL ORANGES  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
599            CHIIILD  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
600             NEKIRU  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
601              NMIXX  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...

[602 rows x 2 columns]

In [130]:
df = df.drop_duplicates(ignore_index=True)

In [131]:
df

                      name                                                url
0                      트레저  https://ticketimage.interpark.com/PlayDictiona...
1                    두아 리파  https://ticketimage.interpark.com/PlayDictiona...
2                       싸이  https://ticketimage.interpark.com/PlayDictiona...
3                      이문세  https://ticketimage.interpark.com/PlayDictiona...
4                    SG워너비  https://ticketimage.interpark.com/PlayDictiona...
..                     ...                                                ...
549                 육중완 밴드  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
550  CHO TOKIMEKI SENDENBU  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
551                    eaJ  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
552                 NEKIRU  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
553                  NMIXX  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...

[554 rows x 2 columns]

In [178]:
df.to_csv('../ticketMerge/artist_total.csv')

In [132]:
# 띄어쓰기 없는 가수명으로 파일 추가 저장

In [133]:
df['name'] = df['name'].str.replace(' ','' )

In [134]:
df

                    name                                                url
0                    트레저  https://ticketimage.interpark.com/PlayDictiona...
1                   두아리파  https://ticketimage.interpark.com/PlayDictiona...
2                     싸이  https://ticketimage.interpark.com/PlayDictiona...
3                    이문세  https://ticketimage.interpark.com/PlayDictiona...
4                  SG워너비  https://ticketimage.interpark.com/PlayDictiona...
..                   ...                                                ...
549                육중완밴드  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
550  CHOTOKIMEKISENDENBU  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
551                  eaJ  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
552               NEKIRU  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...
553                NMIXX  https://i.namu.wiki/i/Bge3xnYd4kRe_IKbm2uqxlhQ...

[554 rows x 2 columns]

In [136]:
df.to_csv('../ticketMerge/artist_total(띄어쓰기x).csv')